### PR TITLE
removing top level biocontainers

### PR DESCRIPTION
**Pull request by vsoch**
these are assumed to be deprecated in favor of the quay.io versions

@muffato I think you suggested doing this once - but now it's fairly important! 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by muffato** [comment]
In principle, yes, but I've spotted some issues
- [quay.io/biocontainers/emboss/container.yaml](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/emboss/container.yaml) and [quay.io/biocontainers/tabix/container.yaml](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/quay.io/biocontainers/tabix/container.yaml) have no aliases ! Both emboss and tabix are very common tools, and are likely to be embedded as dependencies in other biocontainers. Perhaps their tools were discarded by the count threshold ?
- Before removing [biocontainers/picard](https://github.com/singularityhub/shpc-registry/blob/9ff92fbaa4c449ed8853426566a33206f62c0290/biocontainers/picard/container.yaml), can you import https://quay.io/repository/biocontainers/picard ? It somehow didn't make the cut
- I can't find a match for [biocontainers/picard-tools](https://github.com/singularityhub/shpc-registry/blob/main/biocontainers/picard-tools/container.yaml) but anyway it has no aliases, so is probably not a big loss

**Comment by vsoch** [comment]
@muffato working on the alias fixes now - that was a bug!

For containers that are totally absent, it's likely because we couldn't derive binaries for the cache (which is how we determine they are there.) What we will need to do is parse the global list again in the update biocontainers script, and subset that to those we haven't seen yet (and then add them).

**Comment by muffato** [comment]
Taking a look at `quay.io/biocontainers/picard`, there are many things in `/usr/local/bin`, mostly java and other such dependencies. I appreciate many could be filtered out as being found in other base images, but the specific executable of this container, `picard`, _is_ there:

```console
$ singularity pull docker://quay.io/biocontainers/picard:2.27.4--hdfd78af_0
$ singularity shell picard_2.27.4--hdfd78af_0.sif 
Singularity> echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Singularity> ls /usr/local/bin | wc
      306       306      4088
Singularity> ls -l /usr/local/bin/picard 
lrwxrwxrwx    1 root     root            31 Jun 29 19:38 /usr/local/bin/picard -> ../share/picard-2.27.4-0/picard
```

Are you discarding symlinks by any chance ?

**Comment by vsoch** [comment]
I don't believe I'm doing any special filtering for symlinks - it's basically a listing of the directory and then anything found statically is included. Come to think of it - we probably want to _follow_ the symlinks when we originally parse the binary with guts. Unless that symlink (in the context of running inside the container) will function as expected?

**Comment by vsoch** [comment]
@muffato I merged the changed in, mostly to get the recipes there! I set an upper threshold, and in retrospect I'm not sure this was the right decision - e.g., picard doesn't show up. It's count is 15 so it theoretically should be there - I'm going to take a look and see if there is a bug. I think it might be that it was there before, and thus not added again. I'm going to (locally) try running the scripts again, and I'll check. I'll keep this issue open with our discussion until I've been able to try that!

**Comment by vsoch** [comment]
Phew! Found two bugs - confirms that something was up! Running again, should have an update after I watch some good TVs :)

**Comment by vsoch** [comment]
okay I've checked all of the issues above are fixed in my (TBA) PR which I'm going to merge, because it's a huge improvement over the current state!

**Comment by muffato** [comment]
Hi @vsoch . The latest updates look very good. There are much fewer differences, and I noticed that some are due to looking at different versions of the software, which would be OK.

emboss is recalcitrant, though ! The [aliases shpc has](https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/emboss/container.yaml#L10-L27) aren't really the useful binaries :/
The [cache](https://github.com/singularityhub/shpc-registry-cache/blob/main/quay.io/biocontainers/e/emboss:6.6.0--haa49230_5.json) seems correctly populated. Some important commands to keep would be `einverted`, `needle`,`transeq`. Do you know why they were not selected ? Is it because they're too common ? `einverted` is seen 17 times

**Comment by vsoch** [comment]
I think it's a numbers game - we add everything under 10 without question, but then we only add the next 10 (so there were so many binaries we missed those at 17). Should we filter out those that start with underscore?

**Comment by vsoch** [comment]
here is the issue - even removing the underscore ones, there are a ton of binaries < 20:

```
 'aaindexextract': 17,
 'abiview': 17,
 'acdc': 17,
 'acdgalaxy': 17,
 'acdlog': 17,
 'acdpretty': 17,
 'acdtable': 17,
 'acdtrace': 17,
 'acdvalid': 17,
 'aligncopy': 17,
 'aligncopypair': 17,
 'antigenic': 17,
 'assemblyget': 17,
 'backtranambig': 17,
 'backtranseq': 17,
 'banana': 17,
 'biosed': 17,
 'btwisted': 17,
 'cachedas': 17,
 'cachedbfetch': 17,
 'cacheebeyesearch': 17,
 'cacheensembl': 17,
 'chaos': 17,
 'charge': 17,
 'checktrans': 17,
 'cirdna': 17,
 'codcmp': 17,
 'codcopy': 17,
 'coderet': 17,
 'compseq': 17,
 'cons': 17,
 'consambig': 17,
 'cpgplot': 17,
 'cpgreport': 17,
 'cusp': 17,
 'cutgextract': 17,
 'cutseq': 17,
 'dan': 17,
 'dbiblast': 17,
 'dbifasta': 17,
 'dbiflat': 17,
 'dbigcg': 17,
 'dbtell': 17,
 'dbxcompress': 17,
 'dbxedam': 17,
 'dbxfasta': 17,
 'dbxflat': 17,
 'dbxgcg': 17,
 'dbxobo': 17,
 'dbxreport': 17,
 'dbxresource': 17,
 'dbxstat': 17,
 'dbxtax': 17,
 'dbxuncompress': 17,
 'degapseq': 17,
 'density': 17,
 'descseq': 17,
 'diffseq': 17,
 'distmat': 17,
 'dotmatcher': 17,
 'dotpath': 17,
 'dottup': 17,
 'dreg': 17,
 'drfinddata': 17,
 'drfindformat': 17,
 'drfindid': 17,
 'drfindresource': 17,
 'drget': 17,
 'drtext': 17,
 'edamdef': 17,
 'edamhasinput': 17,
 'edamhasoutput': 17,
 'edamisformat': 17,
 'edamisid': 17,
 'edamname': 17,
 'edialign': 17,
 'einverted': 17,
 'emma': 17,
 'emowse': 17,
 'entret': 17,
 'epestfind': 17,
 'eprimer3': 17,
 'eprimer32': 17,
 'equicktandem': 17,
 'est2genome': 17,
 'etandem': 17,
 'extractalign': 17,
 'extractfeat': 17,
 'featcopy': 17,
 'featmerge': 17,
 'featreport': 17,
 'feattext': 17,
 'findkm': 17,
 'freak': 17,
 'fuzznuc': 17,
 'fuzzpro': 17,
 'fuzztran': 17,
 'garnier': 17,
 'geecee': 17,
 'getorf': 17,
 'godef': 17,
 'goname': 17,
 'helixturnhelix': 17,
 'hmoment': 17,
 'iep': 17,
 'infoalign': 17,
 'infoassembly': 17,
 'infobase': 17,
 'inforesidue': 17,
 'infoseq': 17,
 'isochore': 17,
 'jaspextract': 17,
 'jaspscan': 17,
 'lindna': 17,
 'listor': 17,
 'makenucseq': 17,
 'makeprotseq': 17,
 'marscan': 17,
 'maskambignuc': 17,
 'maskambigprot': 17,
 'maskfeat': 17,
 'maskseq': 17,
 'matcher': 17,
 'megamerger': 17,
 'merger': 17,
 'msbar': 17,
 'mwcontam': 17,
 'mwfilter': 17,
 'needleall': 17,
 'newcpgreport': 17,
 'newcpgseek': 17,
 'newseq': 17,
 'nohtml': 17,
 'noreturn': 17,
 'nospace': 17,
 'notab': 17,
 'notseq': 17,
 'nthseq': 17,
 'nthseqset': 17,
 'octanol': 17,
 'oddcomp': 17,
 'ontocount': 17,
 'ontoget': 17,
 'ontogetcommon': 17,
 'ontogetdown': 17,
 'ontogetobsolete': 17,
 'ontogetroot': 17,
 'ontogetsibs': 17,
 'ontogetup': 17,
 'ontoisobsolete': 17,
 'ontotext': 17,
 'palindrome': 17,
 'pasteseq': 17,
 'patmatdb': 17,
 'patmatmotifs': 17,
 'pepcoil': 17,
 'pepdigest': 17,
 'pepinfo': 17,
 'pepnet': 17,
 'pepstats': 17,
 'pepwheel': 17,
 'pepwindow': 17,
 'pepwindowall': 17,
 'plotcon': 17,
 'plotorf': 17,
 'polydot': 17,
 'preg': 17,
 'prettyplot': 17,
 'prettyseq': 17,
 'primersearch': 17,
 'printsextract': 17,
 'profit': 17,
 'prophecy': 17,
 'prophet': 17,
 'prosextract': 17,
 'pscan': 17,
 'psiphi': 17,
 'rebaseextract': 17,
 'recoder': 17,
 'redata': 17,
 'refseqget': 17,
 'remap': 17,
 'restover': 17,
 'restrict': 17,
 'revseq': 17,
 'seealso': 17,
 'seqcount': 17,
 'seqmatchall': 17,
 'seqret': 17,
 'seqretsetall': 17,
 'seqretsplit': 17,
 'seqxref': 17,
 'seqxrefget': 17,
 'servertell': 17,
 'showalign': 17,
 'showdb': 17,
 'showfeat': 17,
 'showorf': 17,
 'showpep': 17,
 'showseq': 17,
 'showserver': 17,
 'shuffleseq': 17,
 'sigcleave': 17,
 'silent': 17,
 'sirna': 17,
 'sixpack': 17,
 'sizeseq': 17,
 'skipredundant': 17,
 'skipseq': 17,
 'splitsource': 17,
 'splitter': 17,
 'stretcher': 17,
 'stssearch': 17,
 'supermatcher': 17,
 'syco': 17,
 'taxget': 17,
 'taxgetdown': 17,
 'taxgetrank': 17,
 'taxgetspecies': 17,
 'taxgetup': 17,
 'tcode': 17,
 'textget': 17,
 'textsearch': 17,
 'tfextract': 17,
 'tfm': 17,
 'tfscan': 17,
 'tmap': 17,
 'tranalign': 17,
 'transeq': 17,
 'trimest': 17,
 'trimseq': 17,
 'trimspace': 17,
 'twofeat': 17,
 'union': 17,
 'urlget': 17,
 'variationget': 17,
 'vectorstrip': 17,
 'water': 17,
 'whichdb': 17,
 'wobble': 17,
 'wordcount': 17,
 'wordfinder': 17,
 'wordmatch': 17,
 'wossdata': 17,
 'wossinput': 17,
 'wossname': 17,
 'wossoperation': 17,
 'wossoutput': 17,
 'wossparam': 17,
 'wosstopic': 17,
 'yank': 17,
 'cai': 18,
 'chips': 18,
 'extractseq': 18,
 'needle': 18,
```
How should we filter this set?

**Comment by muffato** [comment]
In my mind, only the "true" emboss container needs its commands, and any biocontainer that has emboss as a _dependency_ doesn't need to expose them (because they'd still be available from within the container when needed).

The rule could therefore be: if biocontainer_A's commands are a superset of biocontainer_B's, then A shouldn't expose any of B's. Need to consider that A may be a superset of both B and C, and therefore exclude both of their commands. This rule would essentially be an extension of how shpc-guts works, and that way, counts are not involved and there are no thresholds.

**Comment by vsoch** [comment]
We wouldn’t have an easy way to diff some main executable with its dependencies because most are packaged / built in the same layer, or if not, we still couldn’t tell without having some intelligent labeling of layers and then modifying guts to extract only a subset. As an example, installing from a package manager is usually one layer.

https://github.com/BioContainers/containers/blob/master/aegean/0.15.2dfsg-1-deb/Dockerfile

I like the idea but I don’t see how it would be possible to do, at least without some significant work. That said, I’m willing to explore this - we’d arguably need to bring in metadata from package managers and have certainty about which libs and binaries are provided by each install vs dependency. @muffato do you have an idea where this info could come from for bio containers? It feels very SBOM oriented.

**Comment by muffato** [comment]
I wasn't thinking of anything that complex: just comparing the cache you already have. I've built such a script locally, which I'll share in the form of a PR so that you can see how it works. It's not perfect anyway, because for instance `secapr:2.2.8--pyh5e36f6f_0` does *not* come up as a proper super-set of `emboss:6.6.0--haa49230_5` because it contains Python 3.8 executables instead of Python 3.7, and different samtools executables. It feels like the Conda package manager decided to fulfil differently a Python 3 dependency, something I was not accounting for.

**Comment by vsoch** [comment]
@muffato we could definitely have that as a fallback for containers that we can't dump to the filesystem! If you want to give it a shot, the script to edit (and line where you would do this fallback) is here! https://github.com/singularityhub/shpc-registry-cache/blob/601c5503c5314d4bbe9ad98c00c99952f83549ba/.github/scripts/update_biocontainers.py#L125

**Pull request merged**
