### PR TITLE
update nvidia containers and remove sbom/vex artifacts

### LINKED ISSUE #194: Support for nvcr.io/nvidia/pytorch:24.01-py3
**Is your feature request related to a problem? Please describe.**

Missing pytorch:24.01 container.

**Describe the solution you'd like**

SHPC adds support for http://nvcr.io/nvidia/pytorch:24.01-py3

**Describe alternatives you've considered**

[nvcr.io/nvidia/pytorch:24.01-py3](http://nvcr.io/nvidia/pytorch:24.01-py3) provides torch 2.2. which has important improvements. JUWELS-BOOSTER package will likely take months and pip install does not work there due to network config.

### PR DESCRIPTION
**Pull request by vsoch**
This will close #194

### CODE REVIEW

**Comment by clessig** [comment]
Great, thank you. 

I can't directly test it since I use shpc on JUWELS and I need to wait until the package is updated there.

**Comment by vsoch** [comment]
If you clone that PR branch and change the registry entry in your settings.yaml to that clone path root it will install from it. It’s a filesystem registry.

**Comment by vsoch** [comment]
I'm happy to merge without that, but if it goes in (and fails in CI) I'll have to undo the addition. Or if there is another issue I'd ask you to please follow up with a PR. Let me know your preference! It would be ideal to test.

**Comment by clessig** [comment]
Hi, please go ahead and merge. I won't have time to test it at the moment. (I am just using shpc at the moment so figuring out how and where to change the settings.yaml etc would take me some time, which I unfortunately don't have at the moment.)

**Comment by vsoch** [comment]
Also your interest in this container led me to find a bug with tag parsing - nvidia recently added vex and sbom (as tags) and we weren't filtering them out! Now we are. So thank you!

**Pull request merged**
