### PR TITLE
Add/biocontainers

### PR DESCRIPTION
**Pull request by vsoch**
This is a huge PR that will (eventually) be merged to add over 8K biocontainers (with aliases!) to shpc. This uses a simple algorithm that starts with counts across all aliases, and then takes any aliases in the container with count <= 10, and then the next lowest 25. These counts come from https://github.com/singularityhub/shpc-registry-cache, which also has/will have additional automated updates.

Before this is merged here, I need to work on a new update strategy - I'm thinking of starting with hashes of the names (to make the distribution of first letters more equal) and then splitting into chunks to run across the month. More TBA! For now, let's review the aliases chosen (and algorithm).

### CODE REVIEW

**Comment by muffato** [comment]
You're so brave ! https://media.giphy.com/media/SUm90ACYSAE1QtasQe/giphy-downsized-large.gif

I can def. take a look at the tools I know

**Comment by vsoch** [comment]
okay, time to be brave!

**Comment by vsoch** [comment]
And the next two hurdles I'm anticipating - I think the docs should generate ok (but it may take 1-2 hours, still within run limits!) However if the build is too much for jekyll I'll need to again break it into pieces with bundle exec jekyll build (incrementally) based on the first letters of each container. I've done this before too so I'm fairly confident it will work, will just need tweaking. Oh - the perils of trying to scale something on GitHub actions/GitHub pages!

I'll check progress after dinner.

**Comment by vsoch** [comment]
Holy crap it worked! 
image

An hour isn't so bad! Woot!

**Pull request merged**
