### PR TITLE
Adds recipes for AMD InfinityHub containers

### PR DESCRIPTION
**Pull request by dipietrantonio**
Hi there!

This pull request adds recipes for GPU-accelerated applications: cp2k, gromacs, namd, namd3, lammps.

We use these containers at Pawsey to support GPU computations on Setonix.

### CODE REVIEW

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
@dipietrantonio these new containers were breaking CI all over the place - if you look at the actions tab failures it looks like they had unicode characters or similar. I've reverted https://github.com/singularityhub/shpc-registry/compare/main...delete-amd?quick_pull=1 and please recreate the files, and do an shpc update on a linux system for each to ensure they work before opening another PR. thanks!

**Comment by marcodelapierre** [comment]
Thanks @vsoch , I will have a look as well, and provide feedback to @dipietrantonio for his PR.

**Comment by vsoch** [comment]
Thank you! And let me know if I can help. I reverted it quickly because everything failed yesterday (and I thought it might just be one tag that I tried fixing) but when it started happening today I realized the best thing to do would be to revert and carefully go through each one.

**Comment by marcodelapierre** [comment]
> Thank you! And let me know if I can help. I reverted it quickly because everything failed yesterday (and I thought it might just be one tag that I tried fixing) but when it started happening today I realized the best thing to do would be to revert and carefully go through each one.

No worries, I think we will be fine, seems just a few syntax/conventions issues. We are full on these days here, and didn't get to spend time sitting with Cristian to go through this together at least once. I will comment one of the recipes, so he can amend the PR accordingly

**Comment by marcodelapierre** [comment]
Ok @dipietrantonio I have added a review to your PR, to guide you through the editing of the recipes. I have picked the first one to show you.

Please ping me for anything! :)

**Pull request merged**
