### PR TITLE
add script to make it easy to add/remove aliases

### LINKED ISSUE #86: A first look into some of the automated Biocontainers recipes
Hi @vsoch  @audreystott, 

so today I have checked the list of aliases for the 31x Biocontainers recipes we are currently supported on Setonix, our new supercomputer.
The goal is to check for aliases, with dual purpose:
- Pawsey: to make sure we're providing the needed aliases to researchers
- SHPC hub: to provide feedback on the automated alias generation process

So, out of 31 recipes, only 13 had missing aliases, 10 missing them completely, 3 missing only a few of them.
Notably, out of the other recipes, several identified more useful aliases than I had manually, which is great! :-)

[EDIT] The reference, baseline 31 packages are from SHPC release `0.0.57`, under `registry/quay.io/biocontainers/`: https://github.com/singularityhub/singularity-hpc/tree/0.0.57/registry/quay.io/biocontainers 

[EDIT] I have carried out the check on the latest release of the registry, `2023-02`: https://github.com/singularityhub/shpc-registry/tree/2023-02

Here are the recipes with missing packages: bbmap, bcftools, blast, bwa, fastp, gatk, multiqc, mummer, samtools (only some), spades (only some), star, trinity (only one), velvet

Funny fact: cutadapt and spades have python aliases.. I thought those would have been filtered out.

Now, how do we tackle these in general? I am not sure how to improve the algorithm right now, but .. @vsoch can we provide a CLI to add/edits aliases, and make it so that these are retained, both for final use and eventually also for the algorithm to act better?

Thoughts?

### PR DESCRIPTION
**Pull request by vsoch**
This will start to close #86 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by marcodelapierre** [comment]
amazing! will test between today and tomorrow!

oh, now that I think, we might actually benefit for a similar one to tackle the container features, which cannot be picked up at all by the automated approach, because of their nature

**Comment by vsoch** [comment]
Sure! When you have a specific example / use case for the features show me the example and I'll make an equivalent little helper script. It's just loading the container yaml, tweaking it, and saving it, so it's fairly easy to do. I'll likely copy pasta the scripts I just wrote and then change the features. I guess we could also go all out and make a module proper, but that is probably overkill. Probably the best approach is to integrate these functions into shpc proper, and have these clients just use them.

**Comment by marcodelapierre** [comment]
In shpc version `0.0.57`, in `registry/quay.io/biocontainers/`, see `beast2` and `fastqc` for `env:`, and `features:` (the latter right now can have 3 sub-options, `home, `x11` and `gpu`, see https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#registry-yaml-fields)

**Comment by vsoch** [comment]
okay all set!

**Comment by marcodelapierre** [comment]
I have given it a first try:
```
$ python .github/scripts/alias.py add quay.io/biocontainers/fastqc f /usr/local/bin/f
Traceback (most recent call last):
  File "/home/ubuntu/test-v-alias/shpc-registry/.github/scripts/alias.py", line 6, in <module>
    from shpc.main import get_client
ModuleNotFoundError: No module named 'shpc'
```
Is SHPC required to use the helper script? If so, we should mention it in the README

**Comment by marcodelapierre** [comment]
with SHPC installed, I have tested `alias` and `feature`, all good!

**Comment by marcodelapierre** [comment]
last comment: we should have a script for environment variables, too, `env:` section of the yaml, for instance in `quay.io/pawsey/hpc-python/container.yaml`

**Comment by vsoch** [comment]
Ah yes, all of the associated scripts require shpc - I’ll add a comment! And give me a few minutes I’ll add the environment one next.

**Comment by vsoch** [comment]
@marcodelapierre I can't see that container.yaml (maybe private?) can you show me here?

**Comment by vsoch** [comment]
Here is a simple one https://github.com/singularityhub/shpc-registry/blob/main/vanessa/salad/container.yaml

**Comment by vsoch** [comment]
okay added!

**Comment by marcodelapierre** [comment]
Just one comment on the `env` functionality.
It would be good to be able to create empty variables, this is useful e.g. in Python containers to get rid of otherwise host sourced PYTHONic variables, see https://github.com/singularityhub/shpc-registry/blob/main/quay.io/pawsey/hpc-python/container.yaml

Right now:
1. This fails: `python .github/scripts/env.py add quay.io/biocontainers/fastqc variable ''`
2. This succeeds, but then `shpc install` fails: `python .github/scripts/env.py add quay.io/biocontainers/fastqc zia null`. This in fact creates:
    ```
    env:
      variable:
    ```

The desired yaml would be (single or double quotes)
    ```
    env:
      variable: ''
    ```

What do you think?

**Comment by vsoch** [comment]
All set (and yes good testing!)

**Comment by marcodelapierre** [comment]
Sweet! Re-tested, all good for me :)

**Comment by vsoch** [comment]
noice!! Let's merge :) :sunglasses:

**Comment by marcodelapierre** [comment]
Yuppieeee!! :-)
Will update some recipes next week!

**Pull request merged**
