### PR TITLE
Adds a new version of PyTorch.

### PR DESCRIPTION
**Pull request by dipietrantonio**
As per title, this PR adds a new version the Pawsey PyTorch container.

### CODE REVIEW

**Comment by vsoch** [comment]
Have you verified this installs? There are no tokens, etc. needed?

**Comment by dipietrantonio** [comment]
Hi @vsoch, I verified that the container.yaml works. What is a "token" in this case?

**Comment by vsoch** [comment]
I mean you don't need to provide any special tokens to pull the container - it's free to pull publicly.

**Comment by dipietrantonio** [comment]
Thanks for the explanation. Yes it is publicly available.

**Review by vsoch — APPROVED** [review]

**Pull request merged**
